syntax = "proto3";
package monitor.proto;

// 磁盘
message DiskInfo
{
    // 绝对累加计数器
  string name                = 1;             // 磁盘设备名
  uint64 reads               = 2;            // 读操作完成次数
  uint64 writes              = 3;           // 写操作完成次数
  uint64 sectors_read        = 4;     // 累计读取的扇区数 （1扇区 = 512字节）
  uint64 sectors_written     = 5;  // 累计写入的扇区数
  uint64 read_time_ms        = 6;     // 累计读操作花费的毫秒数
  uint64 write_time_ms       = 7;    // 累计写操作花费的毫秒数
  uint64 io_in_progress      = 8;   // 当前正在进行的 IO操作数
  uint64 io_time_ms          = 9;       // 磁盘处于忙碌状态的 总毫秒数
  uint64 weighted_io_time_ms = 10; // 加权IO时间

    // 预留编号

    // 速率/变化率字段
  double read_bytes_per_sec   = 20;     // 当前读吞吐量
  double write_bytes_per_sec  = 21;    // 当前写吞吐量
  double read_iops            = 22;              // 每秒读操作 次数
  double write_iops           = 23;             // 每秒写操作 次数
  double avg_read_latency_ms  = 24;    // 平均读延迟
  double avg_write_latency_ms = 25;   // 平均写延迟
  double util_percent         = 26;           // 磁盘繁忙度
}

/*
 cat /proc/diskstats

 7       0 loop0 63 0 2624 214 0 0 0 0 0 113 214 0 0 0 0 0 0
 7       1 loop1 14 0 34 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 7       2 loop2 50 0 722 91 0 0 0 0 0 52 91 0 0 0 0 0 0
 7       3 loop3 63 0 2164 248 0 0 0 0 0 133 248 0 0 0 0 0 0
 7       4 loop4 341 0 9872 346 0 0 0 0 0 238 346 0 0 0 0 0 0
 7       5 loop5 43 0 694 73 0 0 0 0 0 43 73 0 0 0 0 0 0
 7       6 loop6 61 0 2280 257 0 0 0 0 0 189 257 0 0 0 0 0 0
 7       7 loop7 1698 0 50612 647 0 0 0 0 0 522 647 0 0 0 0 0 0
 2       0 fd0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 8       0 sda 14942 7168 3299210 14675 2263 3709 154408 1036 0 7194 15711 0 0 0 0 0 0
 8       1 sda1 26 0 208 3 0 0 0 0 0 4 3 0 0 0 0 0 0
 8       2 sda2 14805 7168 3294586 14641 2263 3709 154408 1036 0 8270 15677 0 0 0 0 0 0
 11       0 sr0 63 0 4184 44 0 0 0 0 0 35 44 0 0 0 0 0 0
 11       1 sr1 76 0 4196 70 0 0 0 0 0 57 70 0 0 0 0 0 0
 7       9 loop9 46 0 710 112 0 0 0 0 0 99 112 0 0 0 0 0 0
 7       8 loop8 61 0 2162 347 0 0 0 0 0 168 347 0 0 0 0 0 0
 7      10 loop10 1772 0 10682 289 0 0 0 0 0 199 289 0 0 0 0 0 0
 7      11 loop11 57 0 2200 263 0 0 0 0 0 155 263 0 0 0 0 0 0
 7      12 loop12 47 0 756 147 0 0 0 0 0 77 147 0 0 0 0 0 0
 7      13 loop13 45 0 698 155 0 0 0 0 0 84 155 0 0 0 0 0 0
 7      14 loop14 767 0 57972 524 0 0 0 0 0 365 524 0 0 0 0 0 0
 7      15 loop15 46 0 1282 21 0 0 0 0 0 21 21 0 0 0 0 0 0
 7      16 loop16 11 0 28 0 0 0 0 0 0 0 0 0 0 0 0 0 0

 */